
auth:  
  apisource: Polygon.io
  token: TsDjd2WmFwYSsprdEaJkvXlrIRTBlCde
  apiurl: https://api.polygon.io

mysqlsettings:
  dairdb: 'mysql+pymysql://adp_serviceaccount:dairDBPass@my-release-mysql.data.svc.cluster.local:3306/automated_data_pipelines'

finhub:
  token: c7209kqad3ieuiu4i7tg

tickersubscribelist:
- AAL
- MSFT
- TSLA
- AMD 
- AAPL